# Generated by Django 3.0.5 on 2020-04-22 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=512)),
                ('desc', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=512)),
                ('text', models.CharField(max_length=512)),
                ('src_url', models.CharField(max_length=512)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.Shop')),
            ],
        ),
    ]
