# Generated by Django 3.0.5 on 2020-04-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20200422_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='link',
            field=models.CharField(max_length=512),
        ),
    ]
