# Generated by Django 3.0.5 on 2020-04-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20200422_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='src_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='desc',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='link',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
