# Generated by Django 3.0.5 on 2020-04-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20200422_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image_url',
            new_name='image_url1',
        ),
        migrations.AddField(
            model_name='article',
            name='image_url2',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url3',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url4',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
